### ISSUE TITLE
Windows Phone support?

### ISSUE THREAD

**Issue by manggis** [evanshortiss/sns-mobile#16]
Hi!

First of all I would like to thank you for this awesome library. I have a question. Are you planning to add windows phone to supported platforms ?

Thank You, Have a nice day.

**Comment by evanshortiss** [comment]
Thanks! 

I wasn't aware SNS supported Windows since I haven't used it in a while now, so thanks for bringing that to my attention.

I'd be happy to add it to the supported platforms list or accept a PR that does so. I'll try get around to it asap, but I'm a little busy at the moment so it could take a while.

Assuming it works like other platforms you can just add it [here](https://github.com/evanshortiss/sns-mobile/blob/master/lib/interface.js#L8) for the time being and update [this function](https://github.com/evanshortiss/sns-mobile/blob/master/lib/interface.js#L623) with a formatter for the specific type as required.
