### ISSUE TITLE
[Question] How to send data (for example id) to mobile device?

### ISSUE THREAD

**Issue by alimustofa** [evanshortiss/sns-mobile#24]
Hi @evanshortiss, I am using sendMessage to send the notification, but I want to send some data to the mobile device (for example id). Please help me, thanks

**Comment by evanshortiss** [comment]
@alimustofa, not sure I follow, do you mean you want to send a JSON object with extra data? If you take look [here](https://github.com/evanshortiss/sns-mobile/blob/master/lib/interface.js#L619) you can see that the String you pass is converted into the correct format for the device type.

If you want to include custom data you need to pass an Object instead of a String. The Object format for iOS is detailed [here in the "Examples of JSON Payloads" scetion](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html). Other systems have similar documentation.

Hope this is helpful.

**Comment by evanshortiss** [comment]
@alimustofa here's an example based on the iOS link above.

```js
sns.sendMessage(arn, {
    "aps" : {
        "alert" : {
            "title" : "Game Request",
            "body" : "Bob wants to play poker",
            "action-loc-key" : "PLAY"
        },
        "badge" : 5
    },
    "acme1" : "bar",
    "acme2" : [ "bang",  "whiz" ]
}, callback);
```

**Comment by alimustofa** [comment]
Okay thanks @evanshortiss for your fast response, I will try that example.

**Comment by evanshortiss** [comment]
Sure @alimustofa,  best of luck. Closing this. Comment again if you need to open it.
