### ISSUE TITLE
how to send image with message

### ISSUE THREAD

**Issue by sukumardhoni** [evanshortiss/sns-mobile#28]
i am send messages to all devices for which the users registered. How can i send  message along with image. i am using this method to send message to all devices.
sendMessage(endpointArn, message, callback);
//here this method allow two params endpointArn and message.
is there any scope to send image along with that message

**Comment by evanshortiss** [comment]
Hi @sukumardhoni,

I think your best option is to send a URL to load the image via the push notification since Apple and Google both have limits on the push notification sizes. When the user opens the application you can use the URL to fetch the image.

Closing since this is not an issue with this module, but rather an application design question.
